version: '3.8'
services:

  backend:
    container_name: backend
    build:
      context: ./backend
    image: backend:1.0.0
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      OPENAI_API_KEY: dummy_key
    networks:
      - main

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: frontend:1.0.0
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_BACKEND_HTTP_APIURL: dummy_api_url
      NEXT_PUBLIC_HIPPOAI_DISCORD_SERVER_ID: dummy_id
    networks:
      - main

networks:
  main:
