version: "3"
services:
  grobid:
    image: grobid/grobid:0.6.2
    ports:
        - "8070:8070"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
